server:
  port: 8200
  name: demo-server1
spring:
  application:
    name: demo-server1
eureka:      
  instance:
    preferIpAddress: true
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
  client:
    serviceUrl:
      defaultZone: http://regist.server:8100/eureka/
