server:
  port: 8001
  name: demo-server1
spring:
  application:
    name: demo-server1
  zipkin:
    baseUrl: http://localhost:9999/
eureka:      
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://regist.server:8100/eureka/
