server:
  port: 8200
  name: demo-server1
spring:
  application:
    name: demo-server1
  zipkin:
    base-url: http://localhost:8099
sleuth:
  sampler:
    probability: 1
feign:
  hystrix:
    enabled: true
demo-server2:
  ribbon:
    ReadTimeout: 1000
    ConnectTimeout: 1000
    MaxAutoRetries: 1
    MaxAutoRetriesNextServer: 1
logging:
  path: /opt/logs/demo1/
management:
  endpoints:
    web:
      exposure:
        include: '*'
eureka:      
  instance:
    preferIpAddress: true
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
  client:
    serviceUrl:
      defaultZone: http://regist.server:8100/eureka/
