server:
  port: 8200
  name: demo-server1
spring:
  application:
    name: demo-server1
  zipkin:
    base-url: http://localhost:8099
feign:
  hystrix:
    enabled: true
demo-server2:
  ribbon:
    ReadTimeout: 1000
    ConnectTimeout: 1000
    MaxAutoRetries: 1
    MaxAutoRetriesNextServer: 1
logging:
  path: /opt/logs/demo1/
