server:
  port: 8100
  name: demoServer1
spring:
  application:
    name: demo-server1
eureka:      
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://regist.server:8100/eureka/
