server:
  port: 8300
  name: demoServer2
spring:
  application:
    name: demo-server2
management:
  endpoints:
    web:
      exposure:
        include: '*'
eureka:      
  instance:
    preferIpAddress: true
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
  client:
    serviceUrl:
      defaultZone: http://regist.server:8100/eureka/