server:
  port: 8300
  name: demoServer2
spring:
  application:
    name: demo-server2
eureka:      
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://regist.server:8100/eureka/
