eureka:      
  instance:
    preferIpAddress: true
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
  client:
    serviceUrl:
      defaultZone: http://regist.server:8100/eureka/