server:
  port: 8400
spring:
  application:
    name: oauth-server
  zipkin:
    baseUrl: http://localhost:9999
eureka:      
  instance:
    hostname: ${spring.cloud.client.ipAddress}
    instanceId: ${eureka.instance.hostname}:${server.port}
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://regist.server:8100/eureka/