server:
  port: 8200
spring:
  kafka:
    host: localhost
    port: 9092
eureka:      
  instance:
    hostname: ${spring.cloud.client.ipAddress}
    instanceId: ${eureka.instance.hostname}:${server.port}
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://regist.server:8100/eureka/