server:
  port: 8000
  name: server2
spring:
  application:
    name: gateway-server
  zipkin:
    baseUrl: http://localhost:9999/
  cloud:
    gateway:
      routes:
        - id: demo1
          uri: lb://demo-server1
          predicates:
          - Path=/test1/
eureka:      
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://regist.server:8100/eureka/
