server:
  port: 8000
  name: server2
spring:
  application:
    name: gateway-server
  zipkin:
    baseUrl: http://localhost:9999/
eureka:      
  instance:
    instanceId: ${eureka.instance.hostInfo.ipAddress}:${server.port}
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://regist.server:8100/eureka/
