server:
  port: 8000
spring:
  application:
    name: gateway-server
eureka:
  instance:
    hostname: ${spring.cloud.client.ipAddress}
    instanceId: ${eureka.instance.hostname}:${server.port}
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://regist.server:8100/eureka/