server:
  port: 8000
  name: gateway-server
spring:
  application:
    name: gateway-server
  zipkin:
    baseUrl: http://localhost:9999/
  cloud:
    gateway:
      routes:
        - id: demo1
          uri: lb://demo-server1
          predicates:
          - Path=/demo1/**
          filters:
          - StripPrefix=1
        - id: demo2
          uri: lb://demo-server2
          predicates:
          - Path=/demo2/**
          filters:
          - StripPrefix=1
management:
  endpoints:
    web:
      exposure:
        include: '*'
