server:
  port: 8000
  name: server2
spring:
  application:
    name: gateway-server
  zipkin:
    baseUrl: http://localhost:9999/
eureka:      
  instance:
    hostname: ${spring.cloud.client.ipAddress}
    instanceId: ${eureka.instance.hostname}:${server.port}
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://regist.server:8100/eureka/
zuul:
  routes:
    wechat-server:
      path: /wechat/**
      serviceId: wechat-server
      strip-prefix: false